### ISSUE TITLE
Enable CVAR

### ISSUE THREAD

**Issue by busheezy** [gamemann/CSGO_DecoyDodgeball#1]
Can you make a cvar to enable/disable this plugin entirely?  I am setting up a server with all types of game modes and would love to use this plugin.

**Comment by gamemann** [comment]
Hey, I have just implemented the ConVar ("sm_db_enabled"). Plugin was updated to version 1.9.

Thanks for the suggestion!

Thanks.

**Comment by busheezy** [comment]
Hey man.  I appreciate you taking the time to do this even though it is simple.

I saw on your github that you're learning web stuff.
If you ever have any questions feel free to send me a message.
http://steamcommunity.com/id/Ryan/
