### ISSUE TITLE
sm_db_give_enabled

### ISSUE THREAD

**Issue by busheezy** [gamemann/CSGO_DecoyDodgeball#2]
Can you add this for maps that provide the decoys in the center of the map?

**Comment by gamemann** [comment]
Yes, I will implement this tomorrow :)

Thanks.

**Comment by gamemann** [comment]
Hello, I have implemented this feature in the latest update. However, I did not test it this time since I implemented it at school. I will be back in the next hour and I'll be able to test it. If you have any issues, let me know.

Thanks.
